### ISSUE TITLE
Table caption breaks :page-style "Landscape"

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#209] opened 2022-08-29 13:56 UTC
The following snippet when exported will have a caption in portrait mode, separated from the table.

    #+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
    #+options: author:nil broken-links:mark c:nil creator:nil
    #+options: d:(not "LOGBOOK") date:nil e:t email:nil f:t inline:t num:t
    #+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
    #+options: timestamp:nil title:nil toc:nil todo:t |:t
    #+select_tags: export
    #+exclude_tags: noexport

    #+caption: landscape table
    #+ATTR_ODT: :page-break t :page-style "Landscape"
    #+ATTR_ODT: :style "GriddedTable"
    | 1 | 2 | 3 |
    | 4 | 5 | 6 |
    | 7 | 8 | 9 |

**Comment by kjambunathan** [comment] 2022-09-26 10:44
This is a duplicate of this issue [issue#156: In a captioned table with pagebreak, the pagebreak appears between the table and caption.](https://github.com/kjambunathan/org-mode-ox-odt/issues/156)

**Closed** 2022-09-26 11:55 UTC
